version: "3.1"
services:
    db:
        #? Set container name
        container_name: portfolio_db
        image: mongo:latest

        #? Restart if down
        restart: always

        #? Environment file
        env_file:
            - .env

        #? Ports
        ports:
            - ${PORTFOLIO_DB_PORT}:${PORTFOLIO_DB_PORT}

networks:
    portfolio_cms_network:
        external: false
