version: "3.1"
services:
    auth:
        #? Interactive shell
        stdin_open: true
        tty: true

        #? Set container name
        container_name: portfolio_auth

        #? Build the auth service
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile.prod
        
        #? Environment file
        env_file:
            - '.env'
            - '.env.prod'
        
        #? Set Image name
        image: limebrewofficial/portfolio-cms:${PORTFOLIO_VERSION}

        #? Platform
        platform: linux/arm64/v8

        #? Define entrypoint
        entrypoint: 'npm run start:auth[prod]'

        #? Restart if down
        restart: always

        #? Ports
        ports:
            - ${PORTFOLIO_AUTH_PORT}:${PORTFOLIO_AUTH_PORT}

    api:
        #? Interactive shell
        stdin_open: true
        tty: true

        #? Set container name
        container_name: portfolio_api

        #? Build the api service
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile.prod
        
        #? Environment file
        env_file:
            - '.env'
            - '.env.prod'
        
        #? Set Image name
        image: limebrewofficial/portfolio-cms:${PORTFOLIO_VERSION}

        #? Platform
        platform: linux/arm64/v8

        #? Define entrypoint
        entrypoint: 'npm run start:api[prod]'

        #? Restart if down
        restart: always

        #? Ports
        ports:
            - ${PORTFOLIO_API_PORT}:${PORTFOLIO_API_PORT}
