version: "3.1"
services:
    auth:
        #? Interactive shell
        stdin_open: true
        tty: true

        #? Set container name
        container_name: portfolio_auth

        #? Build the auth service
        build:
            context: .
            dockerfile: ./dockerfiles/prod/Dockerfile.auth

        #? Restart if down
        restart: always

        #? Ports
        ports:
            - "8001:8001"

        #? Environment file
        env_file:
            - ".env.prod"

    api:
        #? Interactive shell
        stdin_open: true
        tty: true

        #? Set container name
        container_name: portfolio_api

        #? Build the api service
        build:
            context: .
            dockerfile: ./dockerfiles/prod/Dockerfile.api

        #? Restart if down
        restart: always

        #? Ports
        ports:
            - "8002:8002"

        #? Environment file
        env_file:
            - ".env.prod"
