version: "3.1"
services:
    auth:
        #? Interactive shell
        stdin_open: true
        tty: true

        #? Set container name
        container_name: portfolio_auth
        
        #? Environment file
        env_file:
            - '.env'
            - '.env.prod'
        
        #? Set Image name
        image: limebrewofficial/portfolio-cms:${PORTFOLIO_VERSION}

        #? Define entrypoint
        entrypoint: 'npm run start:auth[prod]'

        #? Restart if down
        restart: always

        #? Ports
        ports:
            - ${PORTFOLIO_AUTH_PORT}:${PORTFOLIO_AUTH_PORT}
        
        #? Set network
        networks:
            - portfolio_cms_network

        #? Container dependencies
        depends_on:
            - redis

    api:
        #? Interactive shell
        stdin_open: true
        tty: true

        #? Set container name
        container_name: portfolio_api
        
        #? Environment file
        env_file:
            - '.env'
            - '.env.prod'
        
        #? Set Image name
        image: limebrewofficial/portfolio-cms:${PORTFOLIO_VERSION}

        #? Define entrypoint
        entrypoint: 'npm run start:api[prod]'

        #? Restart if down
        restart: always

        #? Ports
        ports:
            - ${PORTFOLIO_API_PORT}:${PORTFOLIO_API_PORT}
        
        #? Set network
        networks:
            - portfolio_cms_network
        
        #? Container dependencies
        depends_on:
            - redis
    
    redis:
        #? Set container name
        container_name: portfolio_redis

        #? Environment file
        env_file:
            - .env

        #? Official redis Image
        image: redis:7-alpine

        #? restart container
        restart: always

        #? Set network
        networks:
            - portfolio_cms_network

        #? Ports
        ports:
            - ${PORTFOLIO_REDIS_PORT}:${PORTFOLIO_REDIS_PORT}

        #? Entrypoint/Command
        command: redis-server --loglevel warning

networks:
    portfolio_cms_network:
        external: false
