version: "3.1"
services:
    auth:
        #? Interactive shell
        stdin_open: true
        tty: true

        #? Set container name
        container_name: portfolio_auth
        
        #? Environment file
        env_file:
            - '.env'
            - '.env.prod'
        
        #? Set Image name
        image: limebrewofficial/portfolio-cms:${PORTFOLIO_VERSION}

        #? Define entrypoint
        entrypoint: 'npm run start:auth[prod]'

        #? Restart if down
        restart: always

        #? Ports
        ports:
            - ${PORTFOLIO_AUTH_PORT}:${PORTFOLIO_AUTH_PORT}
        
        #? Set network
        networks:
            - portfolio_cms_network

    api:
        #? Interactive shell
        stdin_open: true
        tty: true

        #? Set container name
        container_name: portfolio_api
        
        #? Environment file
        env_file:
            - '.env'
            - '.env.prod'
        
        #? Set Image name
        image: limebrewofficial/portfolio-cms:${PORTFOLIO_VERSION}

        #? Define entrypoint
        entrypoint: 'npm run start:api[prod]'

        #? Restart if down
        restart: always

        #? Ports
        ports:
            - ${PORTFOLIO_API_PORT}:${PORTFOLIO_API_PORT}
        
        #? Set network
        networks:
            - portfolio_cms_network

networks:
    portfolio_cms_network:
        external: false
