version: "3.1"
services:
    auth:
        #? Interactive shell
        stdin_open: true
        tty: true

        #? Set container name
        container_name: portfolio_auth

        #? Build the auth service
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile.dev
        
        #? Environment file
        env_file:
            - '.env'
            - '.env.dev'
        
        #? Set Image name
        image: limebrewofficial/portfolio-cms:${PORTFOLIO_VERSION}-DEV

        #? Define entrypoint
        entrypoint: 'npm run start:auth[dev]'

        #? Restart if down
        restart: always

        #? Volumes
        volumes:
            - "./portfolio:/app/portfolio"

        #? Ports
        ports:
            - ${PORTFOLIO_AUTH_PORT}:${PORTFOLIO_AUTH_PORT}

        #? Container dependencies
        depends_on:
            - db

    api:
        #? Interactive shell
        stdin_open: true
        tty: true

        #? Set container name
        container_name: portfolio_api

        #? Build the auth service
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile.dev
        
        #? Environment file
        env_file:
            - '.env'
            - '.env.dev'
        
        #? Use the previously built image
        image: limebrewofficial/portfolio-cms:${PORTFOLIO_VERSION}-DEV

        #? Define entrypoint
        entrypoint: 'npm run start:api[dev]'

        #? Restart if down
        restart: always

        #? Volumes
        volumes:
            - "./portfolio:/app/portfolio"

        #? Ports
        ports:
            - ${PORTFOLIO_API_PORT}:${PORTFOLIO_API_PORT}

        #? Container dependencies
        depends_on:
            - db
    
    admin:
        #? Interactive shell
        stdin_open: true
        tty: true

        #? Set container name
        container_name: portfolio_admin

        #? Build the auth service
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile.dev
        
        #? Environment file
        env_file:
            - '.env'
            - ".env.dev"

        #? Use the previously built image
        image: limebrewofficial/portfolio-cms:${PORTFOLIO_VERSION}-DEV

        #? Define entrypoint
        entrypoint: 'npm run start:admin[dev]'

        #? Restart if down
        restart: always

        #? Volumes
        volumes:
            - "./portfolio:/app/portfolio"

        #? Ports
        ports:
            - ${PORTFOLIO_ADMIN_PORT}:${PORTFOLIO_ADMIN_PORT}

        #? Container dependencies
        depends_on:
            - db


    db:
        #? Set container name (will be used to access db by container_name)
        container_name: portfolio_db
        image: mongo:latest

        #? Restart if down
        restart: always

        #? Environment file
        environment:
            - MONGO_INITDB_DATABASE=portfolio_db

        #? Ports
        ports:
            - "27017:27017"
