version: "3.1"
services:
    auth:
        #? Interactive shell
        stdin_open: true
        tty: true

        #? Set container name
        container_name: portfolio_auth

        #? Build the auth service
        build:
            context: .
            dockerfile: Dockerfile.auth.dev

        #? Restart if down
        restart: always

        #? Volumes
        volumes:
            - "./portfolio:/app/portfolio"

        #? Ports
        ports:
            - "8000:8000"

        #? Environment file
        env_file:
            - ".env.dev"

        #? Container dependencies
        depends_on:
            - db

    api:
        #? Interactive shell
        stdin_open: true
        tty: true

        #? Set container name
        container_name: portfolio_api

        #? Build the api service
        build:
            context: .
            dockerfile: Dockerfile.api.dev

        #? Restart if down
        restart: always

        #? Volumes
        volumes:
            - "./portfolio:/app/portfolio"

        #? Ports
        ports:
            - "9000:9000"

        #? Environment file
        env_file:
            - ".env.dev"

        #? Container dependencies
        depends_on:
            - db

    db:
        #? Set container name (will be used to access db by container_name)
        container_name: portfolio_db
        image: mongo:latest

        #? Restart if down
        restart: always

        #? Environment file
        environment:
            - MONGO_INITDB_DATABASE=portfoliodb

        #? Ports
        ports:
            - "27017:27017"
