version: "3.1"
services:
    auth:
        #? Interactive shell
        stdin_open: true
        tty: true

        #? Set container name
        container_name: portfolio_auth

        #? Build the auth service
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile.stg

        #? Environment file
        env_file:
            - .env
            - .env.stg

        #? Set Image name
        image: limebrewofficial/portfolio-cms:${PORTFOLIO_VERSION}-STG

        #? Define entrypoint
        entrypoint: 'npm run start:auth[stg]'

        #? Restart if down
        restart: always

        #? Ports
        ports:
            - ${PORTFOLIO_AUTH_PORT}:${PORTFOLIO_AUTH_PORT}

        #? Set network
        networks:
            - portfolio_cms_network

        #? Container dependencies
        depends_on:
            - db

    api:
        #? Interactive shell
        stdin_open: true
        tty: true

        #? Set container name
        container_name: portfolio_api

        #? Build the api service
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile.stg

        #? Environment file
        env_file:
            - .env
            - .env.stg

        #? Set Image name
        image: limebrewofficial/portfolio-cms:${PORTFOLIO_VERSION}-STG

        #? Define entrypoint
        entrypoint: 'npm run start:api[stg]'

        #? Restart if down
        restart: always

        #? Ports
        ports:
            - ${PORTFOLIO_API_PORT}:${PORTFOLIO_API_PORT}

        #? Set network
        networks:
            - portfolio_cms_network

        #? Container dependencies
        depends_on:
            - db

    admin:
        #? Interactive shell
        stdin_open: true
        tty: true

        #? Set container name
        container_name: portfolio_admin

        #? Build the api service
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile.stg

        #? Environment file
        env_file:
            - .env
            - .env.stg

        #? Set Image name
        image: limebrewofficial/portfolio-cms:${PORTFOLIO_VERSION}-STG

        #? Define entrypoint
        entrypoint: 'npm run start:admin[stg]'

        #? Restart if down
        restart: always

        #? Ports
        ports:
            - ${PORTFOLIO_ADMIN_PORT}:${PORTFOLIO_ADMIN_PORT}

        #? Set network
        networks:
            - portfolio_cms_network

        #? Container dependencies
        depends_on:
            - db
    
    redis:
        #? Set container name
        container_name: portfolio_redis

        #? Environment file
        env_file:
            - .env

        #? Official redis Image
        image: redis:7-alpine

        #? restart container
        restart: always

        #? Set network
        networks:
            - portfolio_cms_network

        #? Ports
        ports:
            - ${PORTFOLIO_REDIS_PORT}:${PORTFOLIO_REDIS_PORT}

        #? Entrypoint/Command
        command: redis-server --loglevel warning

        #? Container dependencies
        depends_on:
            - db


    db:
        #? Set container name (will be used to access db by container_name)
        container_name: portfolio_db
        image: mongo:latest

        #? Restart if down
        restart: always

        #? Environment file
        env_file:
            - .env

        #? Ports
        ports:
            - ${PORTFOLIO_DB_PORT}:${PORTFOLIO_DB_PORT}

        #? Set network
        networks:
            - portfolio_cms_network

networks:
    portfolio_cms_network:
        external: false
