name: Docker CI to Docker Hub

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Grab Version from .env file
        run: |
          VER=$(grep PORTFOLIO_VERSION .env | cut -f 2 -d "=" | tr "\"" "\n")
          echo "USERNAME=limebrewofficial" >> $GITHUB_ENV
          echo "VERSION=$VER" >> $GITHUB_ENV
          echo "REPO=portfolio-cms" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: dockerfiles/Dockerfile.prod
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.USERNAME }}/${{ env.REPO }}:${{ env.VERSION }}
